name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev ccache zip unzip openjdk-17-jdk git python3-pip
          pip install --upgrade pip
          pip install buildozer kivy Cython

      - name: Build APK
        run: |
          # إنشاء مجلد التراخيص وقبولها آلياً بنسبة 100%
          mkdir -p ~/.android/sdk/licenses
          printf "24833b29137e6f86114e4000186d2861355201b7\n504667f4c05912d7331036a9f65fb8636914d4d6\n84831b9402111701a56d4130d972d2424fae0a29\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9d5514f83c2829b004d1fee" > ~/.android/sdk/licenses/android-sdk-license
          
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: crypto_agent_apk
          path: bin/*.apk
